modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Witch-Huts/issues"

[[mods]]
	modId="betterwitchhuts"
	version="${file.jarVersion}"
	displayName="YUNG's Better Witch Huts"
	credits="Thanks so much to all my patrons!"
	authors="YUNGNICKYOUNG, Acarii"
	description="Adds new and improved witch huts to swamps!"
	logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts"

[[dependencies.betterwitchhuts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"

[[dependencies.betterwitchhuts]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"

[[dependencies.betterwitchhuts]]
    modId="yungsapi"
    versionRange="[1.19.2-Forge-3.5.0,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"